#!/bin/bash
# Mount one frame alone in index.html and snapshot it: kit/review-frame.sh <frame_id> <duration> <t1,t2,...>
# (index.html is regenerated by assemble-index.mjs for the real cut.)
set -e
P="$(cd "$(dirname "$0")/.." && pwd)"
ID="$1"; D="$2"; AT="$3"
cat > "$P/index.html" <<HTML
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { margin: 0; width: 1920px; height: 1080px; overflow: hidden; background: #FAF8FF; }
      #root { width: 100%; height: 100%; position: relative; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="$D" data-width="1920" data-height="1080">
      <div id="el-$ID" data-composition-id="$ID" data-composition-src="compositions/frames/$ID.html" data-start="0" data-duration="$D" data-track-index="1" data-width="1920" data-height="1080"></div>
    </div>
    <script>
      const tl = gsap.timeline({ paused: true });
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
HTML
cd "$P"
npx -y hyperframes@0.8.94 lint 2>&1 | tail -12
rm -rf "$P/.hyperframes/review/$ID"
npx -y hyperframes@0.8.94 snapshot --at "$AT" --no-end -o ".hyperframes/review/$ID" 2>&1 | grep -v "^\s*$" | tail -4
