// Stages the app-tour source material into assets/tour/.
//   node kit/stage-tour.mjs
//
// 1. The raw app screenshots (1440×900 at 2×) from devpost/screens/raw/, the same
//    captures behind the landing page's screen tour.
// 2. Their callouts, from devpost/screens/shots.js, as assets/tour/shots.js
//    (window.TOUR_SHOTS). Card positions stay on the landing images' 1500×1000
//    canvas; assets/tour-kit.js converts them to page px.
// 3. The app's real emails. They were rendered from src/emails with each template's
//    PreviewProps (react-email render, not pretty-printed) and captured full-length
//    at 680px wide, 2×, with headless Chrome; this copies those captures from
//    EMAIL_DIR when it is set, e.g. EMAIL_DIR=/path/to/captures node kit/stage-tour.mjs.
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const project = join(dirname(fileURLToPath(import.meta.url)), "..");
const screens = join(project, "../../devpost/screens");
const out = join(project, "assets/tour");
mkdirSync(join(out, "raw"), { recursive: true });

for (const f of readdirSync(join(screens, "raw")).filter((f) => f.endsWith(".png"))) {
  copyFileSync(join(screens, "raw", f), join(out, "raw", f));
}

const sandbox = { window: {} };
vm.runInNewContext(readFileSync(join(screens, "shots.js"), "utf8"), sandbox);
const shots = sandbox.window.SHOTS.map((s) => ({
  id: s.id,
  src: `assets/tour/raw/${s.file}`,
  url: s.url,
  eyebrow: s.eyebrow,
  title: s.title,
  callouts: s.callouts,
}));
writeFileSync(
  join(out, "shots.js"),
  `// Generated by kit/stage-tour.mjs from devpost/screens/shots.js — edit the source, then re-run.\n` +
    `// box: [x, y, w, h] in page px (the 1440×900 screenshot); card: top-left on the landing\n` +
    `// images' 1500×1000 canvas (assets/tour-kit.js converts it); to: connector pin on the ring.\n` +
    `window.TOUR_SHOTS = ${JSON.stringify(shots, null, 2)};\n`,
);
console.log(`✓ ${shots.length} shots → assets/tour/shots.js, screenshots → assets/tour/raw/`);

// Emails: [name, css height to keep] — the judge batch capture has empty page below its card.
const EMAILS = [
  ["judge-batch", 560],
  ["agent-inbox", null],
  ["winner", null],
  ["thank-you", null],
];
const emailDir = process.env.EMAIL_DIR;
if (emailDir) {
  for (const [name, keep] of EMAILS) {
    const src = join(emailDir, `email-${name}.png`);
    if (!existsSync(src)) throw new Error(`missing ${src}`);
    const dst = join(out, `email-${name}.png`);
    if (keep) execFileSync("ffmpeg", ["-v", "error", "-y", "-i", src, "-vf", `crop=1360:${keep * 2}:0:0`, dst]);
    else copyFileSync(src, dst);
  }
  console.log(`✓ ${EMAILS.length} emails → assets/tour/email-*.png`);
}
